### ISSUE TITLE
关于controller线程和service线程

### ISSUE THREAD

**Issue by cumtbzy2011** [chang-chao/spring-webflux-async-jdbc-sample#1]
是不是因该始终不阻塞controller线程，而在service层返回Mono或者Flux时就使用subscribeOn或publishOn指定她们在elastic线程池中执行？

**Comment by chang-chao** [comment]
是的，在spring webflux里面，controller线程不应该被阻塞。

**Comment by chang-chao** [comment]
至于应该用应该SubscribeOn 还是ObserveOn的问题，答案是前者。
二者的区别，你可以看下面这幅图，画得很清楚。
http://reactivex.io/documentation/operators/images/schedulers.png
简单来说，SubscribeOn 制定的是消息生产者的scheduler，而ObserveOn指定的是消息的消费者处理所用的scheduler。我们想指定的是查询数据（消息生产者）在自己的scheduler上面执行，不要阻塞请求的处理过程（controller的入口方法），所以应该用SubscribeOn。

供参考。

**Comment by cumtbzy2011** [comment]
这个我后来试过了，如果controller参数是普通对象，那么可以用subscribeOn，如果controller参数是Mono，那么做链式调用的话应该是publishOn，对Mono参数的subscribeOn是无效的
